ERROR 2025-03-16 20:41:39,137 log Internal Server Error: /teacher/2/exams/
Traceback (most recent call last):
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\35196\password\exams\exams\views.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\35196\password\exams\exams\views.py", line 334, in teacher_exams
    return render(request, 'exams/teacher_exams.html', context)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: exams/teacher_exams.html
ERROR 2025-03-16 20:41:39,143 basehttp "GET /teacher/2/exams/ HTTP/1.1" 500 96142
ERROR 2025-03-16 20:41:55,315 log Internal Server Error: /teacher/2/exams/
Traceback (most recent call last):
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\35196\password\exams\exams\views.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\35196\password\exams\exams\views.py", line 334, in teacher_exams
    return render(request, 'exams/teacher_exams.html', context)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: exams/teacher_exams.html
ERROR 2025-03-16 20:41:55,321 basehttp "GET /teacher/2/exams/ HTTP/1.1" 500 96142
ERROR 2025-03-16 20:42:05,700 log Internal Server Error: /teacher/1/exams/
Traceback (most recent call last):
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\35196\password\exams\exams\views.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\35196\password\exams\exams\views.py", line 334, in teacher_exams
    return render(request, 'exams/teacher_exams.html', context)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: exams/teacher_exams.html
ERROR 2025-03-16 20:42:05,705 basehttp "GET /teacher/1/exams/ HTTP/1.1" 500 96177
